### PR TITLE
events: describe qualifier Q&A event

### PR DESCRIPTION
**Pull request by davisjam**

### CODE REVIEW

**Comment by ayaankazerouni** [comment]
I took some pictures at the event. Do you want to put them on the website?

**Comment by davisjam** [comment]
Yes!

**Comment by davisjam** [comment]
@ayaankazerouni Any issues with this PR? You can add your pics in a follow-up.

**Comment by davisjam** [comment]
TODO This does not render well. Need more line spacing.

**Comment by davisjam** [comment]
a399e52 addresses the formatting [concern](https://github.com/mod0/csgc-website/pull/10#issuecomment-359114806).

**Pull request merged**
